name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-test.txt
    
    - uses: actions/upload-artifact@v2
      with:
        name: synthetic-report
        path: examples/test_data_report.html
        if-no-files-found: error
    - uses: actions/upload-artifact@v2
      with:
        name: flight-delays-report
        path: examples/flight_delays_report.html
        if-no-files-found: error
