name: pre-release

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...        
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
